import { router, json, error, db, secrets, storage } from '@appdeploy/sdk';
import { priceCart } from './pricing';
import { realtimeSubscriptionRoutes } from './realtime-subscribers';
import { randomUUID } from 'crypto';

const compactSummary=(value:unknown)=>{const text=JSON.stringify(value);return text.length>450?text.slice(0,447)+'...':text};
const addChunkedMetadata=(params:URLSearchParams,prefix:string,value:unknown)=>{const text=JSON.stringify(value);for(let i=0;i<Math.min(5,Math.ceil(text.length/450));i++)params.set(`metadata[${prefix}_${i}]`,text.slice(i*450,(i+1)*450))};
const safeFilename=(name:string)=>name.replace(/[^a-zA-Z0-9._-]/g,'-').slice(-100)||'reference-file';
const designRequired=(id:string)=>id==='single-custom-shirt'||id==='supporter-shirt'||id==='3d-single'||id==='group-apparel'||id.startsWith('printed-')||id.startsWith('digital-')||id.startsWith('keepsake-')||id.startsWith('sports-')||['dtf-bundle','3d-front-bundle','3d-full-bundle'].includes(id);
const validateDesignIntake=(items:any[])=>{for(const item of items){const id=String(item.productId||'');const configuration=item.configuration||{};if(['individual-team-shirt','3d-approved-team-shirt'].includes(id)&&!String(configuration.graphicReference||'').trim())throw new Error('Team or approved graphic reference is required');if(designRequired(id)&&!String(configuration.designIdea||'').trim())throw new Error('Design details are required for '+id);if(Array.isArray(configuration.referenceFileNames)&&configuration.referenceFileNames.length&&!configuration.usagePermission)throw new Error('Upload permission is required')}};
const sendQuoteConfirmation=async(email:string,reference:string)=>{try{const names=await secrets.listSecretNames();if(!names.includes('RESEND_API_KEY')||!names.includes('CCC_FROM_EMAIL'))return false;const key=await secrets.readSecret('RESEND_API_KEY');const from=await secrets.readSecret('CCC_FROM_EMAIL');const response=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:'Bearer '+key,'Content-Type':'application/json'},body:JSON.stringify({from,to:[email],subject:'Color Create Connect quote request received',text:'We received your Color Create Connect project request. Reference: '+reference+'. Expect a response within 1 to 2 business days.'})});return response.ok}catch{return false}};

export const handler=router({
 'GET /api/_healthcheck':[async()=>json({message:'Success'})],
 'POST /api/uploads':[async({body})=>{const input=(body||{}) as {filename?:string;contentType?:string;content?:string};if(!input.filename||!input.contentType||!input.content)return error('File information is required',400);const approxBytes=Math.floor(input.content.length*.75);if(approxBytes>10*1024*1024)return error('Reference files must be 10 MB or smaller',400);if(!['image/jpeg','image/png','image/heic','image/heif','application/octet-stream'].includes(input.contentType))return error('Unsupported reference file type',400);const path='uploads/'+Date.now()+'-'+randomUUID()+'-'+safeFilename(input.filename);const[ok]=await storage.write([{path,content:input.content,contentType:input.contentType}]);if(!ok)return error('Unable to store reference file',500);return json({path,filename:input.filename,contentType:input.contentType})}],
 'POST /api/price':[async({body})=>{try{const items=((body||{}) as any).items||[];const priced=priceCart(items);return json({items:priced,subtotal:priced.reduce((s:number,x:any)=>s+x.amount,0)})}catch(e){return error(e instanceof Error?e.message:'Unable to price cart',400)}}],
 'POST /api/quotes':[async({body})=>{const quote=(body||{}) as Record<string,unknown>;if(!quote.name||!quote.email||!quote.details)return error('Name, email, and project details are required',400);const[id]=await db.add('quotes',[{...quote,status:'new',createdAt:Date.now()}]);if(!id)return error('Unable to save quote',500);const quoteRef=id.slice(0,8).toUpperCase();const emailConfirmationSent=await sendQuoteConfirmation(String(quote.email),quoteRef);return json({ok:true,quoteRef,emailConfirmationSent})}],
 'POST /api/checkout':[async({body})=>{try{const input=(body||{}) as any;validateDesignIntake(input.items||[]);const priced=priceCart(input.items||[]);const subtotal=priced.reduce((s:number,x:any)=>s+x.amount,0);const digitalOnly=priced.length>0&&priced.every((x:any)=>String(x.productId).startsWith('digital-'));const shipping=digitalOnly||input.fulfillment==='pickup'||subtotal>=75?0:8;const[orderId]=await db.add('orders',[{items:priced,subtotal,shipping,total:subtotal+shipping,fulfillment:input.fulfillment,status:'pending-payment',configurationComplete:true,createdAt:Date.now()}]);if(!orderId)return error('Unable to create order',500);const names=await secrets.listSecretNames();if(!names.includes('STRIPE_SECRET_KEY'))return json({mode:'preview',orderRef:orderId.slice(0,8).toUpperCase(),subtotal,shipping,total:subtotal+shipping});const key=await secrets.readSecret('STRIPE_SECRET_KEY');const origin=typeof input.origin==='string'&&/^https?:\/\//.test(input.origin)?input.origin:'https://example.com';const params=new URLSearchParams();priced.forEach((x:any,i:number)=>{params.set(`line_items[${i}][quantity]`,'1');params.set(`line_items[${i}][price_data][currency]`,'usd');params.set(`line_items[${i}][price_data][unit_amount]`,String(Math.round(x.amount*100)));params.set(`line_items[${i}][price_data][product_data][name]`,String(x.productId));params.set(`line_items[${i}][price_data][product_data][description]`,compactSummary(x.configuration));params.set(`line_items[${i}][price_data][product_data][tax_code]`,String(x.productId).startsWith('digital-')?(String(x.productId).includes('invitation')||String(x.productId).includes('card')?'txcd_10506002':'txcd_10505001'):'txcd_99999999');addChunkedMetadata(params,'item'+i,x.configuration)});if(shipping>0){const i=priced.length;params.set(`line_items[${i}][quantity]`,'1');params.set(`line_items[${i}][price_data][currency]`,'usd');params.set(`line_items[${i}][price_data][unit_amount]`,'800');params.set(`line_items[${i}][price_data][product_data][name]`,'Shipping')}params.set('metadata[order_id]',orderId);params.set('mode','payment');params.set('automatic_tax[enabled]','true');params.set('automatic_payment_methods[enabled]','true');params.set('success_url',origin+'?checkout=success');params.set('cancel_url',origin+'?checkout=cancel');params.set('client_reference_id',orderId);if(!digitalOnly&&input.fulfillment!=='pickup')params.set('shipping_address_collection[allowed_countries][0]','US');const response=await fetch('https://api.stripe.com/v1/checkout/sessions',{method:'POST',headers:{Authorization:'Bearer '+key,'Content-Type':'application/x-www-form-urlencoded'},body:params});const session=await response.json() as any;if(!response.ok)return error(session.error?.message||'Stripe checkout failed',502);return json({url:session.url,orderRef:orderId.slice(0,8).toUpperCase()})}catch(e){return error(e instanceof Error?e.message:'Unable to prepare checkout',400)}}],
 ...realtimeSubscriptionRoutes
});
